
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 9;
  public static final int MOD = 11;
  public static final int PLUS = 8;
  public static final int RPAREN = 15;
  public static final int SUBELAPIZ = 2;
  public static final int FINLINEA = 6;
  public static final int SEMI = 13;
  public static final int GIRADERECHA = 5;
  public static final int LPAREN = 14;
  public static final int NUMBER = 17;
  public static final int EOF = 0;
  public static final int DIVIDE = 10;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int NUMERO = 16;
  public static final int GIRAIZQUIERDA = 4;
  public static final int BAJALAPIZ = 3;
  public static final int UMINUS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUBELAPIZ",
  "BAJALAPIZ",
  "GIRAIZQUIERDA",
  "GIRADERECHA",
  "FINLINEA",
  "MINUS",
  "PLUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "UMINUS",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "NUMERO",
  "NUMBER"
  };
}

